export const icons = {
  performance: 'streamline-ultimate:performance-increase-bold',
  responsive: 'streamline-ultimate:responsive-design-bold',
  learning: 'eos-icons:machine-learning-outlined',
  tailwind: 'skill-icons:tailwindcss-dark',
  experience: 'arcticons:amex-experiences',
  typescript2: 'skill-icons:typescript',
  react_query: 'logos:react-query-icon',
  typescript: 'lineicons:typescript',
  location: 'mingcute:location-fill',
  calendar: 'stash:data-date-solid',
  nextjs: 'skill-icons:nextjs-dark',
  material_UI: 'logos:material-ui',
  star: 'solar:star-bold-duotone',
  react: 'skill-icons:typescript',
  git: 'material-icon-theme:git',
  lamp: 'cuida:lamp-on-outline',
  security: 'ic:sharp-security',
  html: 'akar-icons:html-fill',
  phone: 'mingcute:phone-fill',
  javascript: 'bi:javascript',
  redux: 'skill-icons:redux',
  css: 'akar-icons:css-fill',
  code: 'mingcute:code-fill',
  telegram: 'logos:telegram',
  github: 'ri:github-fill',
  linkedin: 'mdi:linkedin',
  api: 'eos-icons:api',
  email: 'mdi:email',
};

export const summary = {
  summaryEN:
    '    Frontend Developer with 2 years of hands-on experience in JavaScript, HTML, CSS, Tailwind CSS, React, and Next.js I started my journey through an intensive coding bootcamp and later collaborated with the Saftian team on a project basis, working on two e-commerce applications. Passionate about building high-performance, scalable applications with clean code and well-crafted UI/UX. Experienced in leveraging AI tools to improve development speed and code quality.',
};